# Generated by Django 5.1.3 on 2025-02-11 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('WITHIN_SAVINGS', 'Loans within Savings'), ('ABOVE_SAVINGS', 'Loans Above Savings'), ('COVERED_BY_SALARY', 'Loans Covered by Salary'), ('COVERED_BY_STANDING_ORDER', 'Loans Covered by Standing Order'), ('MORTGAGE', 'Mortgage Loans')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(default='SUBMITTED', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanofficer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanofficer'),
        ),
    ]
