# Generated by Django 5.1.3 on 2025-02-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='rating',
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_details',
            field=models.TextField(blank=True, null=True, verbose_name='Collateral Details'),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(default=1, verbose_name='Credit Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Loan Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.TextField(default=1, verbose_name='Loan Purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='member_account_number',
            field=models.CharField(default=11, max_length=20, verbose_name='Member Account Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='member_full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Member Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='member_saving_account',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10, verbose_name="Member's Saving Account"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='member_share',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name="Member's Share"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_period',
            field=models.IntegerField(default=11, verbose_name='Repayment Period (Months)'),
            preserve_default=False,
        ),
    ]
