# Generated by Django 5.1.3 on 2025-02-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_customer_alter_loanofficer_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='capacity_to_repay_score',
            field=models.IntegerField(default=0, verbose_name='Capacity to Repay Score (50 Points)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='capital_status_score',
            field=models.IntegerField(default=0, verbose_name='Capital Status Score (5 Points)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='character_score',
            field=models.IntegerField(default=0, verbose_name='Character Score (30 Points)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_score',
            field=models.IntegerField(default=0, verbose_name='Collateral/Co-Makers Score (10 Points)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_conditions_score',
            field=models.IntegerField(default=0, verbose_name='Credit Conditions Score (5 Points)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_appraisal_score',
            field=models.IntegerField(default=0, verbose_name='Total Appraisal Score (100 Points)'),
        ),
    ]
