# Generated by Django 5.1.3 on 2025-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_capacity_to_repay_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(verbose_name='Loan Amount'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member_saving_account',
            field=models.IntegerField(verbose_name="Member's Saving Account"),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member_share',
            field=models.IntegerField(verbose_name="Member's Share"),
        ),
    ]
