# Generated by Django 5.1.3 on 2025-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='delay_days',
            field=models.IntegerField(default=0, verbose_name='Estimated Delay Days'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(default=0, verbose_name='Credit Score'),
        ),
    ]
