# Generated by Django 5.1.3 on 2025-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_approval_date_loan_delay_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='score_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Score Label'),
        ),
    ]
