# Generated by Django 5.1.3 on 2025-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genre', models.CharField(max_length=100)),
                ('favorite_artists', models.TextField()),
            ],
        ),
    ]
